version: 2.1

orbs:
  node: circleci/node@5.1
  heroku: circleci/heroku@1.2.6

jobs:
  initial_checks:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/
            - package.json
  run_unit_tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: yarn test
          name: Run tests
  build:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - public/


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_test_deploy:
    jobs:
      - initial_checks
      - run_unit_tests:
          requires:
            - initial_checks
      - build:
          requires:
            - run_unit_tests
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main